loginproject/basicapp/urls.py
from django.urls import path
from basicapp import views


app_name = 'basicapp'

urlpatterns = [

    path('regsiter/', views.register, name='register'),
    path('user_login/',views.user_login, name='user_login')

]

loginproject/loginproject/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('basicapp/', include('basicapp.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
    path('admin/', admin.site.urls),
]

loginproject/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

loginproject/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

loginproject/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm,UserProfileInfoForm
from django.contrib.auth.models import User
#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'basicapp_t/index.html')


@login_required(login_url='index')
def special(request):
    return render(request,'basicapp_t/special.html')

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else: print('error')
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basicapp_t/registration.html',
                    {'user_form': user_form,
                     'profile_form': profile_form,
                     'registered': registered})











def user_login(request):


    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'basicapp_t/login.html', {})

loginproject/templates/basicapp_t/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a  class="navbar-brand" href="{% url 'index' %}"></a></li>
          <li><a class="navbar-link" href="{% url 'index' %}">Django</a></li>
          <li><a class="navbar-link" href="{% url 'basicapp:register' %}">Register</a></li>
          {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'basicapp:user_login' %}">Login</a></li>
          {% endif %}
          <li><a  class="navbar-link" href="{% url 'special' %}">Speacial</a></li>

        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}


      {% endblock %}
    </div>
  </body>
</html>

loginproject/templates/basicapp_t/index.html
{% extends 'basicapp_t/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django Level Five</h1>
</div>

{% endblock %}

loginproject/templates/basicapp_t/login.html
{% extends 'basicapp_t/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'basicapp:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

loginproject/templates/basicapp_t/registration.html
{% extends 'basicapp_t/base.html' %}
{% load staticfiles %}

{% block body_block %}

  <div>
    {% if registered %}
      <h1>Thank you for registering!</h1>
      {% else  %}
      <h1>Register here</h1>
      <h3>Fill out the form:</h3>
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="submit" value="Register">
      </form>
    {% endif %}
  </div>

{% endblock %}

loginproject/templates/basicapp_t/special.html
{% extends 'basicapp_t/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Special page</h1>

      
    </div>
  </div>
{% endblock %}